language: java
jdk:
- openjdk11
script: mvn verify -B
before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
after_success:
  - if [ "$POST_COVERAGE" == "true" ]; then mvn -Pcoverage clean prepare-package coveralls:report; fi
sudo: false
cache:
  directories:
  - $HOME/.m2
before_cache:
# don't cache snapshots
- find $HOME/.m2 -name *SNAPSHOT* -exec rm -r "{}" \;
install: true
notifications:
email: false